name: Helm Image Vulnerability Scan

on:
  push:
    branches:
      - main  # Trigger on push to main branch, adjust as necessary
  pull_request:
    branches:
      - main  # Trigger on PR to main branch, adjust as necessary

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # 2. Set up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # 3. Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

    # 4. Extract image information from the Helm values.yaml
    - name: Extract image from values.yaml
      id: extract_image
      run: |
        # Extract the image repository and tag from the values.yaml
        IMAGE_REPO=$(grep -oP 'repository:\s*\K\S+' values.yaml)
        IMAGE_TAG=$(grep -oP 'tag:\s*\K\S+' values.yaml)
        
        # Set the extracted image information as environment variables for the next steps
        echo "IMAGE=${IMAGE_REPO}:${IMAGE_TAG}" >> $GITHUB_ENV
        
        echo "Extracted Image: ${IMAGE_REPO}:${IMAGE_TAG}"

    # 5. Scan the extracted image using Trivy
    - name: Scan image with Trivy
      run: |
        # Scan the extracted image for vulnerabilities
        trivy image --severity HIGH,CRITICAL --exit-code 1 --no-progress ${{ env.IMAGE }}
