curl -X POST \
  -H "Content-Type: application/json" \
  -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
  --data "$(cat <<EOF
{
  "fields": {
    "project": {
      "key": "YOUR_PROJECT_KEY"
    },
    "summary": "Vulnerabilities in ${IMAGE}",
    "description": "${ISSUE_BODY}",
    "issuetype": {
      "name": "Bug"
    }
  }
}
EOF
)" \
  $JIRA_URL/rest/api/2/issue/ \
  --verbose
