curl -X POST \
  -H "Content-Type: application/json" \
  -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
  --data '{
    "fields": {
      "project": {
        "key": "YOUR_PROJECT_KEY"
      },
      "summary": "Vulnerabilities in ${{ env.IMAGE }}",
      "description": "'"$ISSUE_BODY"'",
      "issuetype": {
        "name": "Bug"
      }
    }
  }' \
  $JIRA_URL/rest/api/2/issue/ \
  --verbose
