name: Helm Image Vulnerability Scan

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # 2. Set up Helm (required for working with Helm charts)
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # 3. Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

    # 4. Cache Trivy DB (to avoid hitting rate limits for downloading it every time)
    - name: Cache Trivy DB
      uses: actions/cache@v2
      with:
        path: ~/.cache/trivy
        key: trivy-db-${{ runner.os }}-${{ hashFiles('**/*.yaml', '**/*.yml') }}
        restore-keys: |
          trivy-db-${{ runner.os }}-

    # 5. List repository files for debugging (check location of values.yaml)
    - name: List repository files for debugging
      run: |
        ls -R

    # 6. Extract the image repository and tag from values.yaml
    - name: Extract image from values.yaml
      id: extract_image
      run: |
        IMAGE_REPO=$(grep -oP 'repository:\s*\K\S+' charts/uptime-kuma/values.yaml || echo "not_found")
        IMAGE_TAG=$(grep -oP 'tag:\s*\K\S+' charts/uptime-kuma/values.yaml || echo "latest")

        # Check if the image was found and log
        if [[ "$IMAGE_REPO" == "not_found" ]]; then
          echo "Error: IMAGE_REPO not found in values.yaml"
          exit 1
        fi
        echo "IMAGE=${IMAGE_REPO}:${IMAGE_TAG}" >> $GITHUB_ENV
        echo "Extracted Image: ${IMAGE_REPO}:${IMAGE_TAG}"

    # 7. Scan the extracted image with Trivy
    - name: Scan image with Trivy
      run: |
        # Scan the image with Trivy for vulnerabilities
        echo "Scanning image ${IMAGE} for vulnerabilities..."
        trivy image --severity HIGH,CRITICAL --exit-code 1 --no-progress ${{ env.IMAGE }}
        
    # 8. Optionally: Show results (useful for debugging)
    - name: Display Trivy Scan Results
      run: |
        echo "Trivy scan completed for image ${IMAGE}."
